#ifndef DATABASE_COMUNICATION_H
#define DATABASE_COMUNICATION_H

#include <QtNetwork/QNetworkAccessManager>
#include <QtNetwork/QNetworkRequest>
#include <QtNetwork/QNetworkReply>
#include <QJsonArray>
#include <QJsonObject>
#include <QImage>

#define LIMIT 500//cantidad de tareas a obtener del servidor
#define TIMEOUT 100
#define RETRIES 2
#define DELAY 10
#define USE_TIMEOUT 1

class database_comunication : public QObject
{
    Q_OBJECT

public:

    enum script_result
    {
        ok,
        timeout,
        get_clientes_failed,
        download_cliente_image_failed,
        download_cliente_image_picture_doesnt_exists,
        cliente_to_server_ok,
        update_cliente_to_server_failed,
        create_cliente_to_server_failed,
        delete_cliente_ok,
        delete_cliente_failed,
        save_login_failed,
        get_all_serial_numbers_failed,
        update_tarea_failed,
        update_operator_failed,
        get_operarios_failed,
        delete_operario_ok,
        delete_operario_failed,
        download_operario_image_failed,
        download_operario_image_picture_doesnt_exists,
        update_operario_to_server_failed,
        create_operario_to_server_failed,
        operario_to_server_ok,
        create_tarea_failed,
        create_operator_failed,
        get_all_internal_numbers_failed,
        get_one_operator_tasks_failed,
        get_done_tasks_failed,
        get_tareas_failed,
        update_tareas_fields_to_server_failed,
        update_itacs_fields_to_server_failed,
        update_contadores_fields_to_server_failed,
        delete_contadores_fields_to_server_failed,
        get_contadores_failed,
        get_operators_failed,
        get_marcas_failed,
        get_zonas_failed,
        get_empresas_failed,
        download_empresa_image_failed,
        download_administrador_image_failed,
        download_administrador_image_picture_doesnt_exists,
        download_empresa_image_picture_doesnt_exists,
        get_administradores_failed,
        get_infos_failed,
        get_calibres_failed,
        get_longitudes_failed,
        get_ruedas_failed,
        get_rutas_failed,
        get_causas_failed,
        get_gestores_failed,
        download_gestor_image_failed,
        download_gestor_image_picture_doesnt_exists,
        get_resultados_failed,
        get_emplazamientos_failed,
        get_clases_failed,
        get_tipos_failed,
        get_observaciones_failed,
        get_piezas_failed,
        download_task_image_failed,
        download_user_image_failed,
        download_task_image_picture_doesnt_exists,
        download_file_failed,
        upload_file_failed,
        delete_file_ok,
        delete_marca_ok,
        delete_zona_ok,
        delete_empresa_ok,
        delete_administrador_ok,
        delete_info_ok,
        delete_calibre_ok,
        delete_longitud_ok,
        delete_rueda_ok,
        delete_ruta_ok,
        delete_causa_ok,
        delete_gestor_ok,
        delete_resultado_ok,
        delete_emplazamiento_ok,
        delete_clase_ok,
        delete_tipo_ok,
        delete_observacion_ok,
        delete_pieza_ok,
        delete_file_failed,        
        delete_marca_failed,
        delete_zona_failed,
        delete_info_failed,
        delete_calibre_failed,
        delete_longitud_failed,
        delete_rueda_failed,
        delete_ruta_failed,
        delete_causa_failed,
        delete_gestor_failed,
        delete_resultado_failed,
        delete_emplazamiento_failed,
        delete_clase_failed,
        delete_empresa_failed,
        delete_administrador_failed,
        delete_tipo_failed,
        delete_observacion_failed,
        delete_pieza_failed,
        download_file_doesnt_exists,
        download_file_ok,
        upload_file_ok,
        download_user_image_picture_doesnt_exists,
        upload_task_image_failed,
        upload_user_image_failed,
        update_task_to_server_failed,
        update_contador_to_server_failed,
        create_contador_to_server_failed,
        update_operator_to_server_failed,
        create_task_to_server_failed,
        login_to_server_failed,
        create_operator_to_server_failed,
        task_to_server_ok,
        contador_to_server_ok,
        marca_to_server_ok,
        update_marca_to_server_failed,
        create_marca_to_server_failed,
        update_empresa_to_server_failed,
        create_empresa_to_server_failed,
        empresa_to_server_ok,
        upload_empresa_image_failed,
        upload_administrador_image_failed,
        administrador_to_server_ok,
        update_administrador_to_server_failed,
        create_administrador_to_server_failed,

        get_equipo_operarios_failed,
        delete_equipo_operario_ok,
        delete_equipo_operario_failed,
        equipo_operario_to_server_ok,
        update_equipo_operario_to_server_failed,
        create_equipo_operario_to_server_failed,

        zona_to_server_ok,
        update_zona_to_server_failed,
        create_zona_to_server_failed,
        info_to_server_ok,
        update_info_to_server_failed,
        create_info_to_server_failed,
        calibre_to_server_ok,
        update_calibre_to_server_failed,
        create_calibre_to_server_failed,
        longitud_to_server_ok,
        update_longitud_to_server_failed,
        create_longitud_to_server_failed,
        rueda_to_server_ok,
        update_rueda_to_server_failed,
        create_rueda_to_server_failed,
        ruta_to_server_ok,
        update_ruta_to_server_failed,
        create_ruta_to_server_failed,
        causa_to_server_ok,
        update_causa_to_server_failed,
        create_causa_to_server_failed,
        gestor_to_server_ok,
        update_gestor_to_server_failed,
        create_gestor_to_server_failed,
        resultado_to_server_ok,
        update_resultado_to_server_failed,
        create_resultado_to_server_failed,
        emplazamiento_to_server_ok,
        update_emplazamiento_to_server_failed,
        create_emplazamiento_to_server_failed,
        clase_to_server_ok,
        update_clase_to_server_failed,
        create_clase_to_server_failed,
        tipo_to_server_ok,
        update_tipo_to_server_failed,
        create_tipo_to_server_failed,
        observacion_to_server_ok,
        update_observacion_to_server_failed,
        create_observacion_to_server_failed,
        pieza_to_server_ok,
        update_pieza_to_server_failed,
        create_pieza_to_server_failed,
        delete_itac_ok,
        itac_to_server_ok,
        get_itacs_failed,
        delete_itac_failed,
        update_itac_to_server_failed,
        create_itac_to_server_failed,
        download_itac_image_failed,
        download_itac_image_picture_doesnt_exists,
        operator_to_server_ok,
        delete_task_failed,
        login_failed,
        login_success,
        connection_success,
        download_audio_failed,
        download_audio_doesnt_exists,
        get_tareas_amount_failed,
        get_tareas_custom_query_failed,        
        get_itacs_custom_query_failed,
        get_itacs_amount_failed,
        get_rutas_custom_query_failed,
        get_rutas_amount_failed,
        get_contadores_amount_failed,
        get_contadores_custom_query_failed,
        connection_failed
    };

    enum serverRequestType
    {
        NONE_REQUEST,
        LOGIN,
        SAVE_LOGIN,
        LOGIN_CLIENTE, //solo para web aqui en escritorio no lo utilizo
        GET_CLIENTES,
        UPLOAD_CLIENTE_IMAGE,
        DOWNLOAD_CLIENTE_IMAGE,
        DELETE_CLIENTE,
        UPDATE_CLIENTE,
        CREATE_CLIENTE,
        GET_ONE_TASK,
        GET_TASKS,
        GET_TAREAS_INFORMADAS,
        GET_TAREAS_CUSTOM_QUERY,
        GET_TAREAS_AMOUNT,
        GET_TASKS_GESTOR,
        GET_ITACS_AMOUNT,
        GET_ITACS_CUSTOM_QUERY,
        GET_ITACS,
        GET_RUTAS_CUSTOM_QUERY,
        GET_RUTAS_AMOUNT,
        GET_CONTADORES_CUSTOM_QUERY,
        GET_CONTADORES_AMOUNT,
        GET_CONTADORES,
        GET_ONE_OPERARIO,
        GET_OPERARIOS,
        UPDATE_OPERARIO,
        CREATE_OPERARIO,
        DELETE_OPERARIO,
        UPLOAD_OPERARIO_IMAGE,
        GET_ONE_OPERARIO_TASKS,
        DOWNLOAD_OPERARIO_IMAGE,
        GET_EQUIPO_OPERARIOS,
        CREATE_EQUIPO_OPERARIO,
        UPDATE_EQUIPO_OPERARIO,
        DELETE_EQUIPO_OPERARIO,
        GET_EMPRESAS,
        GET_ADMINISTRADORES,
        GET_MARCAS,
        GET_ZONAS,
        GET_INFOS,
        GET_CALIBRES,
        GET_LONGITUDES,
        GET_RUEDAS,
        GET_RUTAS,
        GET_CAUSAS,
        GET_GESTORES,
        GET_RESULTADOS,
        GET_EMPLAZAMIENTOS,
        GET_CLASES,
        GET_TIPOS,
        GET_OBSERVACIONES,
        GET_PIEZAS,
        GET_FILES_WORK,
        GET_FILES_CLIENT_WORK,
        TEST_CONECTION,

        UPDATE_MARCA,
        UPDATE_ZONA,
        UPDATE_INFO,
        UPDATE_CALIBRE,
        UPDATE_LONGITUD,
        UPDATE_RUEDA,
        UPDATE_RUTA,
        UPDATE_CAUSA,
        UPDATE_GESTOR,
        UPDATE_RESULTADO,
        UPDATE_EMPLAZAMIENTO,
        UPDATE_CLASE,
        UPDATE_EMPRESA,
        UPDATE_ADMINISTRADOR,
        UPDATE_TIPO,
        UPDATE_OBSERVACION,
        UPDATE_PIEZA,
        UPDATE_TAREA,
        UPDATE_TAREA_FIELDS,
        UPLOAD_USER_IMAGE,
        DOWNLOAD_USER_IMAGE,
        CREATE_TAREA,
        DELETE_TAREA,
        DELETE_MARCA,
        DELETE_ZONA,
        DELETE_INFO,
        DELETE_CALIBRE,
        DELETE_LONGITUD,
        DELETE_RUEDA,
        DELETE_RUTA,
        DELETE_CAUSA,
        DELETE_GESTOR,
        DOWNLOAD_GESTOR_IMAGE,
        UPLOAD_GESTOR_IMAGE,
        DELETE_RESULTADO,
        DELETE_EMPLAZAMIENTO,
        DELETE_CLASE,
        DELETE_EMPRESA,
        DELETE_ADMINISTRADOR,
        DELETE_TIPO,
        DELETE_OBSERVACION,
        DELETE_PIEZA,

        DELETE_FILE,
        DOWNLOAD_TASK_IMAGE,
        UPLOAD_TASK_IMAGE,
        GET_DONE_TASKS,
        LOAD_WORK,
        DOWNLOAD_FILE,
        SAVE_WORK,
        SEND_CLIENT_WORK,
        GET_CLIENT_WORK,
        CREATE_ITAC,
        DOWNLOAD_ITAC_IMAGE,
        UPLOAD_ITAC_IMAGE,
        UPDATE_ITAC_WITH_ID,
        UPDATE_ITAC,
        UPDATE_ITAC_FIELDS,
        DELETE_ITAC,
        CREATE_MARCA,
        CREATE_ZONA,
        CREATE_INFO,
        CREATE_CALIBRE,
        CREATE_LONGITUD,
        CREATE_RUEDA,
        CREATE_RUTA,
        CREATE_CAUSA,
        CREATE_GESTOR,
        CREATE_RESULTADO,
        CREATE_EMPLAZAMIENTO,
        CREATE_CLASE,
        CREATE_EMPRESA,
        UPLOAD_EMPRESA_IMAGE,
        DOWNLOAD_EMPRESA_IMAGE,
        UPLOAD_ADMINISTRADOR_IMAGE,
        DOWNLOAD_ADMINISTRADOR_IMAGE,
        CREATE_ADMINISTRADOR,
        CREATE_TIPO,
        CREATE_OBSERVACION,
        CREATE_PIEZA,
        CREATE_CONTADOR,
        UPDATE_CONTADOR,
        UPDATE_CONTADORES_FIELDS,
        DELETE_CONTADORES,
        GET_MULTIPLE_VALUES_FIELDS,
        GET_MULTIPLE_VALUES_FIELDS_CUSTOM_QUERY,
        GET_ALL_COLUMN_VALUES,
        GET_ALL_COLUMN_VALUES_CUSTOM_QUERY,

        TEST_DB_CONNECTION,
        GET_ALL_INTERNAL_NUMBERS,
        GET_ALL_SERIAL_NUMBERS,
        FILTER_TAREAS,
        GET_FILES_TO_UPDATE
    };

    database_comunication();
    ~database_comunication();
    void serverRequest(serverRequestType type, QStringList keys, QStringList values);

    static QJsonObject getJsonObject(QByteArray byte_array);
    static QJsonArray getJsonArray(QByteArray byte_array);
    static QImage getImageFromString(QString str);

    bool checkConnection();
    static bool checkInternetConnection();
    static QByteArray getFileData(QString filename_and_dir);

    void doDownload(const QUrl &url);
    QString saveFileName(const QUrl &url);
    bool saveToDisk(const QString &filename, QIODevice *data);

signals:
    void alredyAnswered(QByteArray, database_comunication::serverRequestType);
    void processedAnswer(int);
    void cancelDownload();

public slots:
    void cancelRequests();
private slots:
    void downloadFinished(QNetworkReply *reply);
    void sslErrors(const QList<QSslError> &errors);

    void onPostAnswer(QNetworkReply* reply);
    void serverAnswer(QByteArray result_data, database_comunication::serverRequestType type);

private:
    serverRequestType tipoPeticion;
    QNetworkAccessManager *networkManager;
    QByteArray builUploadString(QString filename_and_dir ="", QString empresa ="", QString gestor ="");
    QNetworkAccessManager manager;
    QList<QNetworkReply *> currentDownloads;
    QString donwloadDirLocal= "";
};

#endif // DATABASE_COMUNICATION_H
